### ISSUE TITLE
Absence of i18n support

### ISSUE THREAD

**Issue by ayamba-coder** [TatchumNono/lantube-v2#11]
## Problem
The current app lacks the ability to present its content in languages other than English. This may render non-speaking English users uncomfortable to make proper use of the app in their LANs.

## Solution
Add internalization support using any best library that can easily integrate with react.

@FotieMConstant, @TatchumNono, @marcosriani

**Comment by ayamba-coder** [comment]
Let me try work on this if you guys see it necessary for the issue to be addressed

**Comment by FotieMConstant** [comment]
Sure, that will definitely be great!
Thanks @ayamba-coder
