### ISSUE TITLE
Broken module import

### ISSUE THREAD

**Issue by ayamba-coder** [TatchumNono/lantube-v2#9]
Dev server can't locate the SIgnUp from the App module.
## screenshot
![broken-import](https://user-images.githubusercontent.com/64994841/93018959-bad66380-f5cb-11ea-8efa-0756ddba1ce6.png)

This is so because the App module is importing a wrong module due to typo error:  ```import SignUp from '../Login/SignUp';``` meanwhile the file's name is ``` ../Login/Signup```

## solution
Edit the import statement in App.js to reference the correct module's path ``` ../Login/Signup``` or maintain the current codebase's file case-naming convention which is the Pascal Case by renaming Signup.js to SignUp.js
I propose the file should fall within the scope of the convention.

**Comment by FotieMConstant** [comment]
Hi, @ayamba-coder, I'm pretty surprise to get this issue, because I solved it once. However, you can take a look and try to troubleshoot that. right?
